# Generated by Django 4.1.6 on 2023-02-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chatappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatappmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chatappmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
