# Generated by Django 4.1.6 on 2023-02-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_chatappmessage_created_at_chatappmessage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatappmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatappmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
