# Generated by Django 4.1.7 on 2023-03-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_alter_chatappmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatappmessage',
            name='sendername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chatapp.chatappuser'),
        ),
    ]
