# Generated by Django 4.1.7 on 2023-03-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_alter_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='name',
        ),
    ]
